### PR TITLE
Playback settings

### LINKED ISSUE #43: Speed resets when viewing notation
I've noticed that the speed resets to 100bpm for the notation view (as in, what comes up when you "tap on the pattern names below to see the notes"), including when the speed was set as part of the tune file.

For instance, Bhangra is hardcoded to 120bpm, but tapping "Tune" slows it down to 100bpm.

I think it would be helpful for user-set speed at the top level to persist in the notation view, but we should definitely fix the hardcoded speeds being ignored.

### PR DESCRIPTION
**Pull request by timrog**
Keeps the playback settings when navigating between pages. If changing tune, it resets the tempo to the tune default. Fixes #43

### CODE REVIEW

**Comment by timrog** [comment]
@BirchBirchBirch This is Stolen@200bpm with the fixed tempo settings. Are you happy to go with this?

**Comment by BirchBirchBirch** [comment]
There seems to be a small issue where going straight to a spicy tempo tune (i.e. Bhangra/Jericho/Stolen) after first clicking "Listen" keeps the tempo at 100, though going to another tune and then coming back gets the right speed.

Other than that, looks great!

(My pull request on Stolen has a few more tweaks as well so probably worth putting it through anyway.)

**Comment by BirchBirchBirch** [comment]
Also, the example player song seems to keep the same place between different songs if you change tunes without pressing stop (e.g. listen to Funk example for 5 secs, click Karla without pressing stop, Karla example song is paused at 5 secs in). Probably better if it resets each tune change?

**Comment by timrog** [comment]
> There seems to be a small issue where going straight to a spicy tempo tune (i.e. Bhangra/Jericho/Stolen) after first clicking "Listen" keeps the tempo at 100, though going to another tune and then coming back gets the right speed. (I tested it in a Private Browsing tab to reproduce the issue as otherwise it remembers.)

Other than that, looks great!

(My pull request on Stolen has a few more tweaks as well so probably worth putting it through anyway.) 

OK good spot on both of those issues. They should be fixed now

**Pull request merged**
