### PR TITLE
Adds solo buttons

### PR DESCRIPTION
**Pull request by timrog**
image

Adding solo buttons to hopefully do away with having to manage individual parts. Soloing any instrument will automatically turn on "Whistle on all" aka metronome.

### CODE REVIEW

**Comment by BirchBirchBirch** [comment]
Looks great from the preview!

Could we change the metronome sound to something else? (I think for the entire player, even.) The existing one is quite gratingly loud and often makes it hard to hear the part.

I used the shaker sounds in the current individual parts (I'll be glad to see them go!) and I think that would work well, at least as a placeholder.

**Comment by timrog** [comment]
OK @BirchBirchBirch - I've used stick clicks instead now. A bit more subtle. Are you happy that this means we don't need the individual parts any more?

**Comment by BirchBirchBirch** [comment]
I agree that's a better sound, but unfortunately I think something's up with the timing of the stick sounds so it feels like they're very slightly before the beat (unless my ears are playing tricks on me).

But yes, happy we don't need main individual parts anymore. I notice that the alt parts have also disappeared though, which isn't ideal – if we could mark those as having the metronome by default too that would be good. I'll try putting them back in in the pull request.

(Further thought that it might be helpful for the soloing not to apply to the breaks as those make most sense with everyone, but that doesn't need to be decided now.)

**Comment by timrog** [comment]
I’m not hearing the timing issue on my phone or on my laptop. How obvious is it on yours? I don’t know how accurate ROR’s timing should be. I think I’ll merge this for now and look at it separately, but can you send me a recording or something?


https://user-images.githubusercontent.com/809621/232891143-3b8e31c6-9c21-44f2-8652-e69fdf906167.MOV

**Comment by BirchBirchBirch** [comment]
Sorry, been off drumming (imagine, eh!). I hear the same slight discrepancy on your recording, I'm afraid.

I put three samples into a DAW, which to me shows the click a bit out (after the beat, not before, my mistake).

waveforms

 Would you be able to change it to use the shaker as the metronome?

I realise it might not seem like a lot, but we want to help people with how it feels to be totally in time with each other, so having all the attacks line up is important.

**Pull request merged**
