### PR TITLE
Split General Breaks into Core/More

### PR DESCRIPTION
**Pull request by BirchBirchBirch**
As discussed in #71

### CODE REVIEW

**Comment by timrog** [comment]
Good - we just need to fix it because it still has an empty General Breaks in the list for some reason. https://player.xrrhythms.uk/preview/BirchBirchBirch-gen-split/index.html#/listen

**Comment by BirchBirchBirch** [comment]
Hmm, that's odd. In my session it puts some custom breaks in there so maybe that's it? I'll have a look

I assume this wouldn't be going out before the categories UI change, but I'll see if I can get it to sort them first anyway

**Comment by timrog** [comment]
@BirchBirchBirch Is the aim with this to have breaks outside the category headings? Or something else?

Currently it's

*Core tunes*
Core breaks
...

*Common tunes*
More breaks
....

**Comment by BirchBirchBirch** [comment]
Oh right, no, that wasn't the plan 😅 I'll see if I can fix

The idea is

**General breaks**
Core breaks
More breaks

**Core tunes**
...

Better to have "general breaks" and "general" category than just "breaks", I think, as the songs have breaks as well

**Review by timrog — APPROVED** [review]

**Pull request merged**
