### PR TITLE
Reinstate tune filter

### LINKED ISSUE #27: Filtering tunes and breaks by difficulty/commonness
To support newer bands and players, it would be good to have a dropdown in the navigation panel to display "core", "common", "new" and "all" tunes and breaks.

Tunes have category labels already, although this hasn't been carried over to the main XR Player navigation side panel from the RoR Player (though it is still there in the Compose view).

Individual breaks don't have this feature, however, so I propose adding a "category:" field for each break in a tune (and the General Breaks) and displaying or hiding them accordingly.

### PR DESCRIPTION
**Pull request by timrog**
fixes #27

### CODE REVIEW

**Comment by BirchBirchBirch** [comment]
Looks great!

If I add category tags to individual breaks, could we also have them be filtered? (I realise this means adding rather than reinstating things)

**Comment by timrog** [comment]
I’m not sure how that would work because the breaks aren’t in that list. Does it filter  tunes and breaks at the same time? If you filter by a tune tag, do the breaks get hidden that don’t have that tag?

**Comment by BirchBirchBirch** [comment]
That's what I mean, it isn't currently part of the filtering system but I think it would be really helpful if it was. (So a new band/player could see just the core tunes and breaks, and a more advanced band/player could prioritise which more involved breaks to learn based on if they're actually played much nationally.)

Currently, tunes aren't categorised separately from breaks (they don't have category tags at all currently) so they'll always appear with the song if it's there.

If having something like a list of tunes and breaks for each level to check against would be easier than trying to expand the existing category system then let's do that – I really appreciate you doing the harder part of the work and if we can make it less of a bother please just say!

**Comment by timrog** [comment]
Ok i’ll merge this and let’s tackle filtering patterns/breaks separately.

**Pull request merged**
